-- BudgetHomes: complete Supabase database, RLS and Storage setup.
-- Run this file once in Supabase Dashboard > SQL Editor.

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.admin_users
    where user_id = (select auth.uid())
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

create table if not exists public.content_posts (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  excerpt text not null default '',
  body text not null default '',
  category text not null default 'Property Updates',
  language text not null default 'English',
  image_url text not null default '',
  image_alt text not null default '',
  video_url text not null default '',
  meta_title text not null default '',
  meta_description text not null default '',
  author text not null default 'BudgetHomes Editorial',
  status text not null default 'draft' check (status in ('draft', 'published')),
  featured boolean not null default false,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  bhk text not null default 'Not selected',
  budget text not null default 'Not specified',
  visit_date text not null default 'Flexible',
  source text not null default 'website',
  page text not null default '/',
  status text not null default 'new',
  created_at timestamptz not null default now()
);

create table if not exists public.media_assets (
  id bigint generated by default as identity primary key,
  object_key text not null unique,
  url text not null,
  file_name text not null,
  content_type text not null,
  alt_text text not null default '',
  uploaded_by text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.video_items (
  id bigint generated by default as identity primary key,
  title text not null,
  label text not null default 'Flat Tour',
  description text not null default '',
  video_url text not null,
  poster_url text not null default '',
  poster_alt text not null default '',
  orientation text not null default 'landscape'
    check (orientation in ('landscape', 'vertical')),
  status text not null default 'draft' check (status in ('draft', 'published')),
  featured boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;
alter table public.content_posts enable row level security;
alter table public.leads enable row level security;
alter table public.media_assets enable row level security;
alter table public.video_items enable row level security;

drop policy if exists "Admins can read their membership" on public.admin_users;
create policy "Admins can read their membership"
on public.admin_users for select
to authenticated
using (user_id = (select auth.uid()));

drop policy if exists "Published posts are public" on public.content_posts;
create policy "Published posts are public"
on public.content_posts for select
to anon, authenticated
using (status = 'published');

drop policy if exists "Admins manage posts" on public.content_posts;
create policy "Admins manage posts"
on public.content_posts for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Published videos are public" on public.video_items;
create policy "Published videos are public"
on public.video_items for select
to anon, authenticated
using (status = 'published');

drop policy if exists "Admins manage videos" on public.video_items;
create policy "Admins manage videos"
on public.video_items for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Website visitors can create leads" on public.leads;
create policy "Website visitors can create leads"
on public.leads for insert
to anon, authenticated
with check (true);

drop policy if exists "Admins manage leads" on public.leads;
create policy "Admins manage leads"
on public.leads for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins manage media records" on public.media_assets;
create policy "Admins manage media records"
on public.media_assets for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'budgethomes-media',
  'budgethomes-media',
  true,
  52428800,
  array[
    'image/jpeg',
    'image/png',
    'image/webp',
    'image/gif',
    'video/mp4',
    'video/webm',
    'video/ogg'
  ]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Admins upload BudgetHomes media" on storage.objects;
create policy "Admins upload BudgetHomes media"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'budgethomes-media'
  and public.is_admin()
);

drop policy if exists "Admins update BudgetHomes media" on storage.objects;
create policy "Admins update BudgetHomes media"
on storage.objects for update
to authenticated
using (
  bucket_id = 'budgethomes-media'
  and public.is_admin()
)
with check (
  bucket_id = 'budgethomes-media'
  and public.is_admin()
);

drop policy if exists "Admins delete BudgetHomes media" on storage.objects;
create policy "Admins delete BudgetHomes media"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'budgethomes-media'
  and public.is_admin()
);

insert into public.video_items (
  title,
  label,
  description,
  video_url,
  poster_url,
  poster_alt,
  orientation,
  status,
  featured,
  sort_order
)
select *
from (
  values
    (
      '3 BHK Complete Flat Tour',
      '3 BHK',
      'Fair Township ka complete 3 BHK walkthrough.',
      'https://youtu.be/IPvHVd5iHvc?si=asPja69zWMfEKALl',
      '',
      'Fair Township 3 BHK flat tour in Palghar West',
      'landscape',
      'published',
      true,
      1
    ),
    (
      '1 BHK Ready Home Short Tour',
      '1 BHK',
      'Ready-possession 1 BHK ka quick vertical tour.',
      'https://youtube.com/shorts/5tqn5cNVZi8?si=bvUjbE0DfqK5sLDT',
      '',
      'Fair Township 1 BHK ready home tour',
      'vertical',
      'published',
      false,
      2
    ),
    (
      '2 BHK Layout Short Tour',
      '2 BHK',
      '2 BHK layout aur room planning ka quick walkthrough.',
      'https://youtube.com/shorts/1w-MIlqGU8Q?si=ZzlatyAgOfmAimFx',
      '',
      'Fair Township 2 BHK layout tour',
      'vertical',
      'published',
      false,
      3
    )
) as starter (
  title,
  label,
  description,
  video_url,
  poster_url,
  poster_alt,
  orientation,
  status,
  featured,
  sort_order
)
where not exists (select 1 from public.video_items);
